### ISSUE TITLE
[Novonautica] Definición de estilos y diseño base

### ISSUE THREAD

**Issue by EduardoHidalgo** [MarinaVVsoftware/Novonautica-v2#2]
Definir el estilo visual, el diseño y los estilos que tendrá la página de Novonautica.

**Comment by manuelGTZ97** [comment]
https://coolors.co/export/png/2086c7-e2e2e2-424242-303030-212121

**Comment by manuelGTZ97** [comment]
https://xd.adobe.com/spec/5f22f696-b3e4-4c47-7479-d473fb94c170-2913/

**Comment by manuelGTZ97** [comment]
![image](https://user-images.githubusercontent.com/37588547/55909867-9db19000-5ba2-11e9-80ff-732b4c6cb8f6.png)
