### ISSUE TITLE
[Novonautica] Definir UI de la vista Dashboard

### ISSUE THREAD

**Issue by EduardoHidalgo** [MarinaVVsoftware/Novonautica-v2#4]
Definir el diseño de la vista del Dashboard

**Comment by manuelGTZ97** [comment]
![Dashboard – 1](https://user-images.githubusercontent.com/37588547/55907732-29282280-5b9d-11e9-8ebd-74577e384c29.png)
![Dashboard](https://user-images.githubusercontent.com/37588547/55907734-29282280-5b9d-11e9-824f-e915eefa01e2.png)



@EduardoHidalgo
